package routes

import (
	"github.com/Jlenin5/facil_backend/internal/repository"
	"github.com/Jlenin5/facil_backend/internal/repository/human-resources"
	"github.com/Jlenin5/facil_backend/internal/usecase"
	"github.com/Jlenin5/facil_backend/internal/usecase/human-resources"
	"github.com/gorilla/mux"
	"github.com/jmoiron/sqlx"
)

func SetupProtectedRoutes(router *mux.Router, db *sqlx.DB) {
	accountUC := usecase.NewAccountUseCase(repository.NewAccountRepository(db))
	branchOfficeUC := usecase.NewBranchOfficeUseCase(repository.NewBranchOfficeRepository(db))
	brandUC := usecase.NewBrandUseCase(repository.NewBrandRepository(db))
	cashMovementUC := usecase.NewCashMovementUseCase(repository.NewCashMovementRepository(db))
	cashRegisterUC := usecase.NewCashRegisterUseCase(repository.NewCashRegisterRepository(db))
	categoryUC := usecase.NewCategoryUseCase(repository.NewCategoryRepository(db))
	companyUC := usecase.NewCompanyUseCase(repository.NewCompanyRepository(db))
	currencyUC := usecase.NewCurrencyUseCase(repository.NewCurrencyRepository(db))
	customerUC := usecase.NewCustomerUseCase(repository.NewCustomerRepository(db))
	employeeUC := usecase.NewEmployeeUseCase(repository.NewEmployeeRepository(db))
	exchangeRateUC := usecase.NewExchangeRateUseCase(repository.NewExchangeRateRepository(db))
	attendanceTypeUC := usecaseHumanresources.NewAttendanceTypeUseCase(repositoryHumanresources.NewAttendanceTypeRepository(db))
	absenceRequestRoutesUC := usecaseHumanresources.NewAbsenceRequestUseCase(repositoryHumanresources.NewAbsenceRequestRepository(db))
	absenceTypeRoutesUC := usecaseHumanresources.NewAbsenceTypeUseCase(repositoryHumanresources.NewAbsenceTypeRepository(db))
	attendanceRoutesUC := usecaseHumanresources.NewAttendanceUseCase(repositoryHumanresources.NewAttendanceRepository(db))
	employeeBenefitRoutesUC := usecaseHumanresources.NewEmployeeBenefitUseCase(repositoryHumanresources.NewEmployeeBenefitRepository(db))
	employeeIncidentRoutesUC := usecaseHumanresources.NewEmployeeIncidentUseCase(repositoryHumanresources.NewEmployeeIncidentRepository(db))
	employeeScheduleRoutesUC := usecaseHumanresources.NewEmployeeScheduleUseCase(repositoryHumanresources.NewEmployeeScheduleRepository(db))
	holidayRoutesUC := usecaseHumanresources.NewHolidayUseCase(repositoryHumanresources.NewHolidayRepository(db))
	overtimeRequestRoutesUC := usecaseHumanresources.NewOvertimeRequestUseCase(repositoryHumanresources.NewOvertimeRequestRepository(db))
	payrollRoutesUC := usecaseHumanresources.NewPayrollUseCase(repositoryHumanresources.NewPayrollRepository(db))
	payrollDetailRoutesUC := usecaseHumanresources.NewPayrollDetailUseCase(repositoryHumanresources.NewPayrollDetailRepository(db))
	performanceReviewRoutesUC := usecaseHumanresources.NewPerformanceReviewUseCase(repositoryHumanresources.NewPerformanceReviewRepository(db))
	scheduleDetailRoutesUC := usecaseHumanresources.NewScheduleDetailUseCase(repositoryHumanresources.NewScheduleDetailRepository(db))
	vacationRoutesUC := usecaseHumanresources.NewVacationUseCase(repositoryHumanresources.NewVacationRepository(db))
	vacationBalanceRoutesUC := usecaseHumanresources.NewVacationBalanceUseCase(repositoryHumanresources.NewVacationBalanceRepository(db))
	workScheduleRoutesUC := usecaseHumanresources.NewWorkScheduleUseCase(repositoryHumanresources.NewWorkScheduleRepository(db))
	inventoryMovementUC := usecase.NewInventoryMovementUseCase(repository.NewInventoryMovementRepository(db))
	jobPositionUC := usecase.NewJobPositionUseCase(repository.NewJobPositionRepository(db))
	keyUC := usecase.NewKeyUseCase(repository.NewKeyRepository(db))
	opportunityTrackingUC := usecase.NewOpportunityTrackingUseCase(repository.NewOpportunityTrackingRepository(db))
	paymentMethodUC := usecase.NewPaymentMethodUseCase(repository.NewPaymentMethodRepository(db))
	planUC := usecase.NewPlanUseCase(repository.NewPlanRepository(db))
	projectUC := usecase.NewProjectUseCase(repository.NewProjectRepository(db))
	productUC := usecase.NewProductUseCase(repository.NewProductRepository(db))
	purchaseUC := usecase.NewPurchaseUseCase(repository.NewPurchaseRepository(db))
	purchaseOrderUC := usecase.NewPurchaseOrderUseCase(repository.NewPurchaseOrderRepository(db))
	purchaseRequestUC := usecase.NewPurchaseRequestUseCase(repository.NewPurchaseRequestRepository(db))
	quoteUC := usecase.NewQuoteUseCase(repository.NewQuoteRepository(db))
	roleUC := usecase.NewRoleUseCase(repository.NewRoleRepository(db))
	saleOrderUC := usecase.NewSaleOrderUseCase(repository.NewSaleOrderRepository(db))
	saleUC := usecase.NewSaleUseCase(repository.NewSaleRepository(db))
	stockControlUC := usecase.NewStockControlUseCase(repository.NewStockControlRepository(db))
	subscriptionUC := usecase.NewSubscriptionUseCase(repository.NewSubscriptionRepository(db))
	supplierUC := usecase.NewSupplierUseCase(repository.NewSupplierRepository(db))
	systemUC := usecase.NewSystemUseCase(repository.NewSystemRepository(db))
	taxUC := usecase.NewTaxUseCase(repository.NewTaxRepository(db))
	userUC := usecase.NewUserUseCase(repository.NewUserRepository(db))
	warehouseUC := usecase.NewWarehouseUseCase(repository.NewWarehouseRepository(db))
	workAreaUC := usecase.NewWorkAreaUseCase(repository.NewWorkAreaRepository(db))
  
	AccountRoutes(router, accountUC)
	BranchOfficeRoutes(router, branchOfficeUC)
	BrandRoutes(router, brandUC)
	CashMovementRoutes(router, cashMovementUC)
	CashRegisterRoutes(router, cashRegisterUC)
	CategoryRoutes(router, categoryUC)
	CompanyRoutes(router, companyUC)
	CurrencyRoutes(router, currencyUC)
	CustomerRoutes(router, customerUC)
	EmployeeRoutes(router, employeeUC)
	ExchangeRateRoutes(router, exchangeRateUC)
	AttendanceTypeRoutes(router, attendanceTypeUC)
	AbsenceRequestRoutes(router, absenceRequestRoutesUC)
	AbsenceTypeRoutes(router, absenceTypeRoutesUC)
	AttendanceRoutes(router, attendanceRoutesUC)
	EmployeeBenefitRoutes(router, employeeBenefitRoutesUC)
	EmployeeIncidentRoutes(router, employeeIncidentRoutesUC)
	EmployeeScheduleRoutes(router, employeeScheduleRoutesUC)
	HolidayRoutes(router, holidayRoutesUC)
	OvertimeRequestRoutes(router, overtimeRequestRoutesUC)
	PayrollRoutes(router, payrollRoutesUC)
	PayrollDetailRoutes(router, payrollDetailRoutesUC)
	PerformanceReviewRoutes(router, performanceReviewRoutesUC)
	ScheduleDetailRoutes(router, scheduleDetailRoutesUC)
	VacationRoutes(router, vacationRoutesUC)
	VacationBalanceRoutes(router, vacationBalanceRoutesUC)
	WorkScheduleRoutes(router, workScheduleRoutesUC)
	InventoryMovementRoutes(router, inventoryMovementUC)
	JobPositionRoutes(router, jobPositionUC)
	KeyRoutes(router, keyUC)
	OpportunityTrackingRoutes(router, opportunityTrackingUC)
	PaymentMethodRoutes(router, paymentMethodUC)
	PlanRoutes(router, planUC)
	ProjectRoutes(router, projectUC)
	ProductRoutes(router, productUC)
	PurchaseRoutes(router, purchaseUC)
	PurchaseOrderRoutes(router, purchaseOrderUC)
	PurchaseRequestRoutes(router, purchaseRequestUC)
	QuoteRoutes(router, quoteUC)
	RoleRoutes(router, roleUC)
	SaleOrderRoutes(router, saleOrderUC)
	SaleRoutes(router, saleUC)
	StockControlRoutes(router, stockControlUC)
	SubscriptionRoutes(router, subscriptionUC)
	SupplierRoutes(router, supplierUC)
	SystemRoutes(router, systemUC)
	TaxRoutes(router, taxUC)
	UserRoutes(router, userUC)
	WarehouseRoutes(router, warehouseUC)
	WorkAreaRoutes(router, workAreaUC)
}